FROM mborejdo/docker-base
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

RUN /root/.cargo/bin/cargo install wcloud --git https://github.com/isaackd/wcloud-dev &&\
    /root/.cargo/bin/cargo install sic &&\
	/root/.cargo/bin/cargo install --bin wss --git https://github.com/mborejdo/wss --branch main

