FROM mborejdo/docker-base
ENV PATH="/root/.cargo/bin:/root/bin:${PATH}"
COPY --from=mborejdo/docker-rusty /root/.cargo/bin/* /root/.cargo/bin/

ADD /entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]